cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample_minority: true
kfolds: 5
no_print_progress: true
epochs: 10
batch_size: 16
network: cnn_linear
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-kfold-nb20-drop-e.pkl
#train_to_pickle: /fastdata/deepards/unpadded_centered_sequences-kfold-nb20-drop-e.pkl
n_sub_batches: 20
experiment_name: drop_e_lim_unpadded
drop_i_lim: false
drop_e_lim: true
