cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample_minority: true
kfolds: 5
no_print_progress: true
epochs: 5
batch_size: 16
network: cnn_linear
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-kfold.pkl
n_sub_batches: 20
transforms: ie_ww_i_or_e
transform_probability: 0.5
use_i: true
save_model: saved_models/unpadded_centered_sequences-nb20-kfold-i-only-hetero-fix.pth
