data_path: /home/greg/workspace/datasets/ardsdetection/
cohort_file: /home/greg/workspace/python/deepards/deepards/cohort-description.csv
holdout_set_type: main
dataset_type: unpadded_centered_sequences
n_sub_batches: 20
loader_threads: 0
train_from_pickle: unpadded_centered_sequences-nb20-train.pkl
test_from_pickle: unpadded_centered_sequences-nb20-test.pkl
clip_val: 0.01
base_network: densenet18
network: cnn_linear
batch_size: 16
