data_path: /fastdata/ardsdetection/
dataset_type: unpadded_centered_sequences
n_sub_batches: 20
loader_threads: 0
train_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-train-holdout-fold_3_dissimilarity_split.pkl
test_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-test-holdout-fold_3_dissimilarity_split.pkl
#train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-train-holdout-fold_3_dissimilarity_split.pkl
#test_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-test-holdout-fold_3_dissimilarity_split.pkl
clip_val: 0.01
base_network: densenet18
network: cnn_linear
batch_size: 16
cuda_no_dp: true
epochs: 20
holdout_set_type: fold_3_dissimilarity_split
final_validation: true
