cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: padded_breath_by_breath
oversample: true
kfolds: 5
no_print_progress: true
pochs: 10
batch_size: 16
network: lstm_only_with_packing
#train_to_pickle: /fastdata/deepards/padded_breath_by_breath-nb20-kfold.pkl
train_from_pickle: /fastdata/deepards/padded_breath_by_breath-nb20-kfold.pkl
n_sub_batches: 20
