cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample: true
kfolds: 5
no_print_progress: true
epochs: 10
batch_size: 16
network: lstm_only
train_from_pickle: unpadded_centered_sequences-nb20-kfold.pkl
n_sub_batches: 20
transforms: naive_ww
