cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: padded_breath_by_breath
oversample_minority: true
kfolds: 5
no_print_progress: true
epochs: 10
batch_size: 16
network: lstm_only
train_from_pickle: padded_breath_by_breath-nb100-kfold.pkl
n_sub_batches: 100
