cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
loader_threads: 0
oversample: true
#no_print_progress: true
epochs: 15
batch_size: 16
network: protopnet
#train_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-aim1_holdout_train_redo.pkl
#test_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-aim1_holdout_test_redo.pkl
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-aim1_holdout_train_redo.pkl
test_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-aim1_holdout_test_redo.pkl
n_sub_batches: 20
data_path: /fastdata/ardsdetection
holdout_set_type: main
base_network: densenet18
