cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample: true
kfolds: 5
#no_print_progress: true
epochs: 10
batch_size: 16
network: protopnet_2d
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-kfold.pkl
#train_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-kfold.pkl
n_sub_batches: 20
data_path: /fastdata/ardsdetection
# something too large to happen
viz_every_n: 50
viz_start_epoch: 50
