data_path: /fastdata/ardsdetection/
dataset_type: unpadded_centered_sequences
n_sub_batches: 20
loader_threads: 0
#train_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-train-holdout-train_sim_test_sim_dissim.pkl
#test_to_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-test-holdout-train_sim_test_sim_dissim.pkl
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-train-holdout-train_sim_test_sim_dissim.pkl
test_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-test-holdout-train_sim_test_sim_dissim.pkl
clip_val: 0.01
base_network: densenet18
network: cnn_linear
batch_size: 16
cuda_no_dp: true
epochs: 15
holdout_set_type: train_sim_test_sim_dissim
final_validation: true
