cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample: true
kfolds: 5
no_print_progress: true
epochs: 20
batch_size: 16
network: cnn_linear
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-kfold-nb20-truncate-e-50.pkl
#train_to_pickle: /fastdata/deepards/unpadded_centered_sequences-kfold-nb20-truncate-e-50.pkl
n_sub_batches: 20
experiment_name: truncate_e_lim_50
drop_i_lim: false
drop_e_lim: false
truncate_e_lim: .50
