cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample: true
kfolds: 5
no_print_progress: true
epochs: 10
batch_size: 2
network: cnn_linear_2d
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-kfold.pkl
n_sub_batches: 20
data_path: /fastdata/ardsdetection
block_kernel_size: 9
with_fft: true
