cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample_minority: true
kfolds: 5
no_print_progress: true
epochs: 10
batch_size: 16
network: cnn_linear
train_from_pickle: unpadded_centered_sequences-nb100-kfold.pkl
#train_to_pickle: unpadded_centered_sequences-nb100-kfold.pkl
n_sub_batches: 100
experiment_name: unpadded_centered_100_sub_batches
data_path: /home/grehm/workspace/datasets/ardsdetection
