name: deepardsdev3
dependencies:
  - python<3.8
  - cython
  - ipython
  - numpy
  - pandas
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - seaborn
  - scipy
  - scikit-learn<0.23
  - opencv
  - pathlib
  - shap
  - matplotlib
  - pyqt
  - jupyter
  - ipython
  - pip
  - pip:
    - pathlib
    - lime
channels:
  - pytorch
  - conda-forge
