name: deepardsdev3
dependencies:
  - python<3.8
  - cython
  - ipython
  - numpy
  - pandas
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - seaborn
  - scipy>=1.1
  - scikit-learn
  - opencv
  - pathlib
  - shap
  - matplotlib
  - pyqt
  - jupyter
  - ipython
  - statsmodels
  - pyyaml
  - pip
  - pip:
    - pathlib
    - lime
    - build/static/ucdpvanalysis-1.5.tar.gz
    - git+git://github.com/lukauskas/dtwco.git#egg=dtwco
    - imbalanced-learn
    - mock
    - prettytable
channels:
  - pytorch
  - conda-forge
