name: deepardsdev2
dependencies:
  - python=2.7
  - cython
  - ipython
  - numpy
  - pandas
  - pytorch=1.0
  - torchvision
  - cudatoolkit
  - seaborn
  - scipy>=1.1
  - scikit-learn
  - opencv
  - pathlib
  - matplotlib
  - pyqt
  - jupyter
  - ipython
  - statsmodels
  - pyyaml
  - pip
  - pip:
    - pathlib
    - build/static/ucdpvanalysis-1.5.tar.gz
    - git+git://github.com/lukauskas/dtwco.git#egg=dtwco
    - imbalanced-learn=0.4.3
    - mock
    - prettytable
    - shap
