name: deepards
dependencies:
  - python=2.7
  - cython
  - ipython
  - numpy
  - pandas
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - seaborn
  - scipy
  - scikit-learn
  - opencv
channels:
  - pytorch
  - conda-forge
