name: deepardsdev
dependencies:
  - python=2.7
  - cython
  - ipython
  - numpy
  - pandas
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - seaborn
  - scipy
  - scikit-learn
  - opencv
  - pathlib
  - pip
  - pip:
    - pathlib
channels:
  - pytorch
  - conda-forge
