cuda_no_dp: true
clip_val: 0.01
clip_grad: true
dataset_type: unpadded_centered_sequences
oversample: true
kfolds: 5
no_print_progress: true
epochs: 10
batch_size: 16
network: cnn_linear
train_from_pickle: /fastdata/deepards/unpadded_centered_sequences-nb20-kfold.pkl
n_sub_batches: 20
experiment_name: experiment_files_unpadded_centered_nb20_cnn_linear
models:
  0: model-run-1-epoch3-fold0.pth
  1: model-run-1-epoch3-fold1.pth
  2: model-run-1-epoch3-fold2.pth
  3: model-run-1-epoch3-fold3.pth
  4: model-run-1-epoch3-fold4.pth
